module.exports = {
  common: {
    MISSING_INVITE_TOUSER: "Missing Invitation's To User",
    MISSING_INVITE_REQUESTEDTIME: "Missing Invitation's requested time",
    INTERNAL_INVITE_ERROR: "Error sending invitation.",
    INTERNAL_ERROR: "Some error occured",
  },
  ride: {
    MISSING_START_LOCATION: "Missing Ride's Start Location",
    MISSING_END_LOCATION: "Missing Ride's End Location",
    MISSING_START_POINT: "Missing Start Point",
    MISSING_END_POINT: "Missing End Point",
    MISSING_TRAVEL_DATE: "Missing Ride's Travel Date",
    MISSING_TRAVEL_TIME: "Missing Ride's Travel Time",
    MISSING_TRAVEL_DESCRIPTION: "Missing Ride's Travel Description",
    MISSING_INVITE_RIDE: "Missing Invitation's Ride",
    INTERNAL_ERROR: "Error creating ride.",
    INTERNAL_GETTRIPMATCHES_ERROR: "Error retrieving trip matches.",
    INVITATION_ALREADY_SENT: 'An invitation has already been sent to this driver to join this ride.'
  },
  drive: {
    MISSING_START_LOCATION: "Missing Drive's Start Location",
    MISSING_END_LOCATION: "Missing Drive's End Location",
    MISSING_START_POINT: "Missing Start Point",
    MISSING_END_POINT: "Missing End Point",
    MISSING_TRAVEL_DATE: "Missing Drive's Travel Date",
    MISSING_TRAVEL_TIME: "Missing Drive's Travel Time",
    MISSING_AVAILABLE_SEATS: "Missing Drive's Available Seats",
    MISSING_TRAVEL_DESCRIPTION: "Missing Drive's Travel Description",
    MISSING_INVITE_DRIVE: "Missing Invitation's Drive",
    INTERNAL_CREATE_ERROR: "Error creating drive.",
    INTERNAL_GETTRIPMATCHES_ERROR: "Error retrieving trip matches.",
    INVITATION_ALREADY_SENT: 'An invitation has already been sent to this rider to join this drive.'
  },
  user: {
    MISSING_FIRST_NAME: "Missing User's First Name",
    MISSING_LAST_NAME: "Missing User's Last Name",
    MISSING_EMAIL: "Missing User's Email",
    MISSING_SCHOOL: "Missing User's School",
    MISSING_PASSWORD: "Missing User's Password",
    INVALID_PASSWORD: "Invalid password",
    MISSING_USERNAME: "Missing User's Username",
    MISSING_BIRTHDAY: "Missing User's Birthday",
    INTERNAL_ERROR: "Error creating user.",
    INVALID_USERNAME: "Invalid username",
    DUPLICATE_USERNAME: "Duplicate username",
    INVALID_EMAIL: "Invalid email",
    DUPLICATE_EMAIL: "Duplicate email",
    NON_STUDENT_EMAIL: "Non-student email",
    UNVERIFIED_USER: "Unverified user",
    UNAUTHORIZED_USER: "Unauthorized user",
    MISSING_USER_TOKEN: "No token provided",
    INVALID_USER_TOKEN: "Invalid token provided",
    MISSING_EXPO_TOKEN: "expoToken not sent",
  }
}
